# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - never-stale
  - docs
  - bug
  - feature-request
  - help-wanted
# Label to use when marking an issue as stale
# staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had recent activity. It will be closed in a week no further activity occurs. Feel free continue the discussion or ask for a `never-stale` label to keep it open. If this is a support issue, consider sharing it on stack overflow to get more eyes on your problem.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
